using System.Globalization;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Power.Generation.FissionGenerator;
using Content.Shared.Lock;
using Content.Shared.Rounding;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using System.Diagnostics.CodeAnalysis;

namespace Content.Client._FarHorizons.Power.UI;

/// <summary>
/// Client-side UI used to control a turbine.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TurbineWindow : FancyWindow
{
    // Dependencies
    [Dependency] private readonly IEntityManager _entityManager = null!;
    private readonly LockSystem _lock;

    #region Variables
    //Colors for the RPM meter. (lit)
    private static readonly Color[] _speedColors = [
        StyleNano.DangerousRedFore,
        StyleNano.DangerousRedFore,
        StyleNano.DangerousRedFore,
        Color.FromHex("#C49438"),
        Color.FromHex("#C49438"),
        Color.FromHex("#C49438"),
        Color.FromHex("#B3BF28"),
        Color.FromHex("#B3BF28"),
        Color.FromHex("#B3BF28"),
        StyleNano.GoodGreenFore,
        Color.FromHex("#C49438"),
        StyleNano.DangerousRedFore,
    ];

    //Colors for the RPM meter. (unlit)
    private static readonly Color[] _speedColorsDim =
    [
        DimStorageColor(_speedColors[0]),
        DimStorageColor(_speedColors[1]),
        DimStorageColor(_speedColors[2]),
        DimStorageColor(_speedColors[3]),
        DimStorageColor(_speedColors[4]),
        DimStorageColor(_speedColors[5]),
        DimStorageColor(_speedColors[6]),
        DimStorageColor(_speedColors[7]),
        DimStorageColor(_speedColors[8]),
        DimStorageColor(_speedColors[9]),
        DimStorageColor(_speedColors[10]),
        DimStorageColor(_speedColors[11]),
    ];

    // Style boxes for the RPM meter.
    private StyleBoxFlat[] _speedMeter;

    private int _speedLevel;

    private EntityUid _turbine;

    private bool _isMonitor = false;
    private EntityUid _monitor;

    private bool _suppressSliderEvents;
    #endregion

    #region Events
    public event Action<float>? TurbineFlowRateChanged;
    public event Action<float>? TurbineStatorLoadChanged;
    #endregion

    public TurbineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _lock = _entityManager.System<LockSystem>();

        InitRPMMeter();

        // Handle flow rate
        TurbineFlowRateLabel.OnFocusExit += _ => CommitFlowRateText();
        TurbineFlowRateLabel.OnTextEntered += _ => CommitFlowRateText();

        TurbineFlowRateSlider.OnValueChanged += _ =>
        {
            if (!_suppressSliderEvents)
                TurbineFlowRateChanged?.Invoke(TurbineFlowRateSlider.Value);
        };
        FlowRateDecrease.OnPressed += _ => ApplyFlowRate(TurbineFlowRateSlider.Value - 100);
        FlowRateIncrease.OnPressed += _ => ApplyFlowRate(TurbineFlowRateSlider.Value + 100);

        // Handle stator load
        TurbineStatorLoadLabel.OnFocusExit += _ => CommitStatorLoadText();
        TurbineStatorLoadLabel.OnTextEntered += _ => CommitStatorLoadText();

        TurbineStatorLoadSlider.OnValueChanged += _ =>
        {
            if (!_suppressSliderEvents)
                TurbineStatorLoadChanged?.Invoke(TurbineStatorLoadSlider.Value);
        };
        StatorLoadDecreaseLarge.OnPressed += _ => ApplyStatorLoad(TurbineStatorLoadSlider.Value - 1000);
        StatorLoadDecrease.OnPressed += _ => ApplyStatorLoad(TurbineStatorLoadSlider.Value - 100);
        StatorLoadIncrease.OnPressed += _ => ApplyStatorLoad(TurbineStatorLoadSlider.Value + 100);
        StatorLoadIncreaseLarge.OnPressed += _ => ApplyStatorLoad(TurbineStatorLoadSlider.Value + 1000);

        CTabContainer.SetTabTitle(0, Loc.GetString("comp-turbine-ui-tab-main"));
        CTabContainer.SetTabTitle(1, Loc.GetString("comp-turbine-ui-tab-parts"));
    }

    private void CommitFlowRateText()
    {
        if (!TryParseInput(TurbineFlowRateLabel.Text, out var num))
            return;

        ApplyFlowRate(num);
    }

    private void CommitStatorLoadText()
    {
        if (!TryParseInput(TurbineStatorLoadLabel.Text, out var num))
            return;

        ApplyStatorLoad(num);
    }

    private void ApplyFlowRate(float value)
    {
        var clamped = Math.Clamp(value, TurbineFlowRateSlider.MinValue, TurbineFlowRateSlider.MaxValue);
        _suppressSliderEvents = true;
        TurbineFlowRateSlider.Value = clamped;
        TurbineFlowRateLabel.Text = Math.Round(clamped).ToString(CultureInfo.InvariantCulture);
        _suppressSliderEvents = false;
        TurbineFlowRateChanged?.Invoke(clamped);
    }

    private void ApplyStatorLoad(float value)
    {
        var clamped = Math.Clamp(value, TurbineStatorLoadSlider.MinValue, TurbineStatorLoadSlider.MaxValue);
        _suppressSliderEvents = true;
        TurbineStatorLoadSlider.Value = clamped;
        TurbineStatorLoadLabel.Text = Math.Round(clamped).ToString(CultureInfo.InvariantCulture);
        _suppressSliderEvents = false;
        TurbineStatorLoadChanged?.Invoke(clamped);
    }

    private static bool TryParseInput(string text, out float value)
    {
        return float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out value)
            || float.TryParse(text, NumberStyles.Float, CultureInfo.CurrentCulture, out value);
    }

    #region Graphics
    public void SetEntity(EntityUid turbine, EntityUid? monitor = null)
    {
        _turbine = turbine;

        if (monitor != null)
        {
            _monitor = monitor.Value;
            _isMonitor = true;
        }

        this.SetInfoFromEntity(_entityManager, _isMonitor ? _monitor : _turbine);

        EntityView.SetEntity(turbine);
    }

    [MemberNotNull(nameof(_speedMeter))]
    public void InitRPMMeter()
    {
        _speedMeter = new StyleBoxFlat[_speedColors.Length];

        for (var i = _speedColors.Length - 1; i >= 0; i--)
        {
            var styleBox = new StyleBoxFlat();
            _speedMeter[i] = styleBox;

            for (var j = 0; j < RPMMeter.Columns; j++)
            {
                var control = new PanelContainer
                {
                    Margin = new Thickness(2),
                    PanelOverride = styleBox,
                    HorizontalExpand = true,
                    VerticalExpand = true,
                };
                RPMMeter.AddChild(control);
            }
        }
    }

    private static Color DimStorageColor(Color color)
    {
        var hsv = Color.ToHsv(color);
        hsv.Z /= 5;
        return Color.FromHsv(hsv);
    }

    public void Update(TurbineBuiState msg)
    {
        UpdateIndicators(msg);

        if (!TurbineFlowRateLabel.HasKeyboardFocus())
            TurbineFlowRateLabel.Text = Math.Round(msg.FlowRate).ToString(CultureInfo.InvariantCulture);

        if (!TurbineStatorLoadLabel.HasKeyboardFocus())
            TurbineStatorLoadLabel.Text = Math.Round(msg.StatorLoad).ToString(CultureInfo.InvariantCulture);

        var locktarget = _isMonitor ? _monitor : _turbine;
        Inputs.Visible = !_lock.IsLocked(locktarget);
        LockedMessage.Visible = _lock.IsLocked(locktarget);

        _suppressSliderEvents = true;
        TurbineFlowRateSlider.MaxValue = msg.FlowRateMax;
        TurbineFlowRateSlider.MinValue = msg.FlowRateMin;
        TurbineFlowRateSlider.Value = msg.FlowRate;

        TurbineStatorLoadSlider.MaxValue = msg.StatorLoadMax;
        TurbineStatorLoadSlider.MinValue = msg.StatorLoadMin;
        TurbineStatorLoadSlider.Value = msg.StatorLoad;
        _suppressSliderEvents = false;

        _speedLevel = ContentHelpers.RoundToNearestLevels(msg.RPM, msg.BestRPM * 1.2, _speedMeter.Length);

        BladeInfoIntegrity.Text = Math.Round(msg.Health * 100 / msg.HealthMax).ToString() + "%";
        BladeInfoStress.Text = Math.Round(msg.RPM * 100 / (msg.BestRPM * 1.2)).ToString() + "%";

        StatorInfoPotential.Text = FormatPower(msg.PowerGeneration);
        StatorInfoSupply.Text = FormatPower(msg.PowerSupply);
    }

    private static string FormatPower(float power) => Loc.GetString("battery-menu-power-value", ("value", power));

    private void UpdateIndicators(TurbineBuiState msg)
    {
        var FilePath = "/Textures/_FarHorizons/Structures/Power/Generation/FissionGenerator/indicator_lamps/";
        // These are just if/else statements in black magic form
        TurbineOverspeed.TexturePath = msg.Overspeed ? FilePath + "redlit.png" : FilePath + "reddim.png";
        TurbineOvertemp.TexturePath = msg.Overtemp ? FilePath + "redlit.png" : FilePath + "reddim.png";
        TurbineStalling.TexturePath = msg.Stalling ? FilePath + "amberlit.png" : FilePath + "amberdim.png";
        TurbineUndertemp.TexturePath = msg.Undertemp ? FilePath + "bluelit.png" : FilePath + "bluedim.png";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        for (var i = 0; i < _speedMeter.Length; i++)
        {
            var box = _speedMeter[i];
            if (_speedLevel > i)
            {
                // On
                box.BackgroundColor = _speedColors[i];
            }
            else
            {
                box.BackgroundColor = _speedColorsDim[i];
            }
        }
    }
    #endregion
}